###################################自定义配置##########################################
core:
    default:
        password: 123456
        avatar: /assets/picture/default-avatar.png
    shiro:
        # session 过期时长，单位：毫秒
        session-timeout: 1800000
        # 检测有效 session 间隔时长
        interval: 900000
        cookie-timeout: 604800