###################################基础配置##########################################
server:
  tomcat:
    # tomcat 编码
    uri-encoding: UTF-8
    # tomcat 最大线程数，默认值 200
    max-threads: 500
    # Tomcat 空闲线程数，默认值 10
    min-spare-threads: 30
  port: 8080

# spring 配置
spring:
    application:
        name: freedom-boot
    profiles:
        active: @profiles.active@
        # 引入其他模块的 yml 文件
        include:
          - business
          - core
          - generator
          - monitor
          - file
          - task
          - terminal
    thymeleaf:
        mode: HTML5
        encoding: UTF-8
        # 禁止缓存
        cache: false
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    servlet:
        multipart:
            # 文件上传大小
            max-file-size:  30MB
            # 请求数据大小
            max-request-size:  30MB
    messages:
        basename: i18n/messages
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            # 主库配置
            master:
                url: @master.url@
                username: @master.username@
                password: @master.password@
            # 从库配置
            slave:
                enabled: @slave.enabled@
                url: @slave.url@
                username: @slave.url@
                password: @slave.url@
            # druid 专属配置
            filters: stat,log4j
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: select 'x'
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
            useGlobalDataSourceStat: true
            connectionProperties: druid.stat.slowSqlMillis=2000

# mybatis 配置
mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    # 配置各个模块的 mapper 文件路径
    mapper-locations:
      - classpath:mybatis/mapper/core/*.xml
      - classpath:mybatis/mapper/generator/*.xml
      - classpath:mybatis/mapper/monitor/*.xml
      - classpath:mybatis/mapper/file/*.xml
      - classpath:mybatis/mapper/task/*.xml
# 通用 mapper 配置
mapper:
    mappers:
        - com.extlight.common.base.BaseMapper
    not-empty: false
    identity: MYSQL

# 分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
